### ISSUE TITLE
not sure why this didn't work

### ISSUE THREAD

**Issue by waynenilsen** [jjuliano/markdown-ui#1]
based on the code that this created

```
> Inverted Blue Segment:
> > Inverted Blue Menu:
> > [Markdown UI](#home "basic")
> > > Inverted Blue Right Menu:
> > > [Docs](#docs)
> > > [About](#about)
> > > [Github](#github)
> > > [Install](#install)
```

i tried to do something similar trying to replicate http://semantic-ui.com/examples/homepage.html but got stuck on the header

```
> Large Top Fixed Hidden Menu:
> > Container:
> > > [home](#home "active item")
> > > [work](#work)
> > > [play](#play)
```

any ideas? here is the dump

```
/var/lib/gems/2.1.0/gems/markdown-ui-0.1.0/lib/markdown-ui/content/parser.rb:25:in `parse': undefined method `split' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.1.0/gems/markdown-ui-0.1.0/lib/markdown-ui/menu/custom.rb:13:in `render'
	from /var/lib/gems/2.1.0/gems/markdown-ui-0.1.0/lib/markdown-ui/menu/element.rb:35:in `render'
	from /var/lib/gems/2.1.0/gems/markdown-ui-0.1.0/lib/markdown-ui.rb:78:in `block in block_quote'
	from /var/lib/gems/2.1.0/gems/markdown-ui-0.1.0/lib/markdown-ui.rb:115:in `html'
	from /var/lib/gems/2.1.0/gems/markdown-ui-0.1.0/lib/markdown-ui.rb:63:in `block_quote'
	from /var/lib/gems/2.1.0/gems/markdown-ui-0.1.0/exe/markdown-ui:31:in `render'
	from /var/lib/gems/2.1.0/gems/markdown-ui-0.1.0/exe/markdown-ui:31:in `<top (required)>'
	from /usr/local/bin/markdown-ui:23:in `load'
	from /usr/local/bin/markdown-ui:23:in `<main>'
```

**Comment by jjuliano** [comment]
The third quote is not inline with the container

It should be

> Large Menu:
> > Container:
> > [home](#home "active")
...

**Comment by waynenilsen** [comment]
yep, should have noticed, thanks
